CODETOOLS-7903756 - jcstress shuld not pass debugging parameters to subproceses
openjdk/jcstress pull request #150
Opened 2024-07-02 10:38 UTC by judovana

No longer passing any -agentlib to subprocesses, unless it is part of -jvmArgsPrepend, thus allowing to debug both jcstress itself or wrked vm as expected:

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005  -jar tests-all/target/jcstress.jar -c 1 -jvmArgsPrepend "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5006"

works.

2024-07-02 17:00 UTC, matcdac requested changes

2024-07-03 08:46 UTC, judovana commented on jcstress-core/src/main/java/org/openjdk/jcstress/Options.java
> +    }
Hi! I made it ab it more strict (`-agentlib:jdwp`)  and renamed the method.

2024-07-03 08:50 UTC, judovana commented on jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
> +        List<String> l = Options.filterAgentLib(orig.args);
Sure. That was leftower. I had moved the method directly ty VMSupport.java and made it private.
Unless you insists I would like to keep method in. I will inline it with comment if you say anyway.

2024-07-03 08:52 UTC, judovana commented
Hello! Thanx a lot for review. 

The https://github.com/openjdk/jcstress/pull/119 can be closed with its corresponding bug of  https://bugs.openjdk.org/browse/CODETOOLS-7903266 ,  if we agree on merging this (#150) . I had noticed the bug and the PR only I drafted my PR. Sorry.

2024-07-03 19:39 UTC, matcdac requested changes
other than the imports it looks good to me

2024-07-03 19:39 UTC, matcdac commented on jcstress-core/src/main/java/org/openjdk/jcstress/Options.java
> +import java.util.stream.Collectors;
this import is not required now

2024-07-03 19:39 UTC, matcdac commented on jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
> +import java.util.stream.Collectors;
same here as well

2024-07-04 06:22 UTC, judovana commented on jcstress-core/src/main/java/org/openjdk/jcstress/TestExecutor.java
> +import java.util.stream.Collectors;
sorry for that. both gone now.

2024-07-04 08:01 UTC, matcdac approved these changes
looks good to me, ready to merge

2024-07-04 08:08 UTC, judovana commented
/integrate

2024-07-04 10:12 UTC, judovana commented
> @judovana This pull request has not yet been marked as ready for integration.

Hmm, then we need approver and sponsor?

2024-07-04 16:24 UTC, judovana commented
/integrate

2024-07-08 10:37 UTC, shipilev approved these changes
This looks okay, but I would probably just inline `removeJdwpAgentLib` into `cleanArgs` and re-indent the stream as the code around does it (ops on different lines, collect as the last line). The single-line helper method does not carry its weight, IMO.

2024-07-08 10:37 UTC, shipilev commented on jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
> +    private static List<String> removeJdwpAgentLib(List<String> originalArgs ) {
```suggestion
    private static List<String> removeJdwpAgentLib(List<String> originalArgs) {
```

2024-07-08 10:38 UTC, shipilev requested changes
Wait, let's make sure it passes the GHA tests, enable the workflows first, and then update the PR.

2024-07-08 10:43 UTC, judovana commented
hi! Ty!

The only reason to not inline the `removeJdwpAgentLib` is need of comment instead of separate method.   But I do not have strong preference.  TYVM for eyball and GH!

2024-07-08 14:31 UTC, shipilev commented
Please do the following:
1. Inline `removeJdwpAgentLib`.
2. Enable GHA tests and pass them.

2024-07-08 15:48 UTC, shipilev approved these changes
Only stylistic nits, otherwise good. Fix those, and once GHA is green, we can integrate.

2024-07-08 15:48 UTC, shipilev commented on jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
> +        List<String> l = orig.args.stream().filter(s -> !s.startsWith("-agentlib:jdwp")).collect(Collectors.toList());
```suggestion
        List<String> l = orig.args.stream()
            .filter(s -> !s.startsWith("-agentlib:jdwp"))
            .collect(Collectors.toList());
```

2024-07-08 15:48 UTC, shipilev commented on jcstress-core/src/main/java/org/openjdk/jcstress/vm/VMSupport.java
> +        configs = configs.stream()
```suggestion

        // Filter out unwanted arguments.
        configs = configs.stream()
```

2024-07-08 15:52 UTC, judovana commented
Cool. All except MACs are green.

2024-07-09 05:21 UTC, judovana commented
/integrate

2024-07-09 08:12 UTC, shipilev commented
/sponsor

2024-07-09 08:13 UTC, closed without merging